### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by dpackage** [pcbje/pyanx#1]
Hello Petter,

I was able to run the pyanx_test and create the test_probe.anx file, but I'm trying to replicate the link strength settings found in the ANB install folder example "fraud chart.xml"

When I add the strength references manually to a project I'm working on it throws errors on import to ANB with messages like "unable to delete LNStrengthReference from default".  Comparing it to fraud chart, I think what's missing is the CurrentStyleSelection and/or the LinkEntityTypeCollection.

Do you have an example unit test with the minimum to allow link strengths to be specified and import to execute without error when opening in ANB?

Thanks,
Dan

**Comment by pcbje** [comment]
Hi,

Link strength is currently not supported.

Look at LinkStyle, Strength and DotStyle classes in anx.py. You'll need to add DotStyle (string value) to function [add_edge](https://github.com/pcbje/pyanx/blob/master/pyanx/pyanx.py#L43) and use it to create a valid strength in in  [__add_links](https://github.com/pcbje/pyanx/blob/master/pyanx/pyanx.py#L96)
